version: 2.1
executors:
  debian:
    docker:
    - image: cimg/python:3.7
  node:
    docker:
      - image: cimg/node:14.17.6

commands:
  install_k8s_dependencies:
    description: Install dependencies for deploying to K8s cluster
    steps:
      - run:
          name: Install kubectl
          command: |
            sudo apt-get update -y && sudo apt-get install -y curl
            sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            kubectl config set-credentials jalbot --token=$JALBOT_TOKEN
            kubectl config set-cluster prod --server=$K8S_SERVER --insecure-skip-tls-verify=true
            kubectl config set-context jalbot --cluster=prod --user=jalbot
            kubectl config use-context jalbot
      - run:
          name: Install helm
          command: |
            sudo apt-get install apt-transport-https gnupg2 --yes
            sudo curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
            sudo echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
            sudo apt-get update
            sudo apt-get install -y helm
  install_version_dependencies:
    description: Install dependencies for versioning
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y git jq
  check_tags:
    description: Check if git tag matches package.json version
    steps:
      - run:
          name: Check tags
          command: |
            VERSION=$(jq -r .version package.json | tr -d '"')
            GIT_TAG=$(git describe)
            echo "Version: ${VERSION} | Tag: ${GIT_TAG}"
            if [ "$VERSION" != "$GIT_TAG" ]; then
                circleci-agent step halt
            fi

jobs:
  lint:
    executor: node
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install dependencies and run lint
          command: |
            npm install
            npx eslint .

  build_and_publish:
    executor: debian
    resource_class: large
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Image
          command: |
            export WAVELENGTHS_VERSION=$(jq -r .version package.json | tr -d '"')
            docker build \
              -t wavelengths:$WAVELENGTHS_VERSION \
              --build-arg google_api_key=$GOOGLE_API_KEY \
              --build-arg node_env=production .
          environment:
            DOCKER_BUILDKIT: 1
      - check_tags
      - run:
          name: Publish image
          command: |
            export WAVELENGTHS_VERSION=$(jq -r .version package.json | tr -d '"')
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
            docker tag wavelengths:$WAVELENGTHS_VERSION $DOCKER_USERNAME/wavelengths:$WAVELENGTHS_VERSION
            docker push $DOCKER_USERNAME/wavelengths:$WAVELENGTHS_VERSION

  deploy:
    circleci_ip_ranges: false
    executor: debian
    steps:
      - checkout
      - install_version_dependencies
      - check_tags
      - install_k8s_dependencies
      - run:
          name: Add Helm repo
          command: |
            helm repo add beantown $HELM_REPO
            kubectl config get-contexts
            kubectl get pods -n prod
      - run:
          name: Deploy wavelengths-frontend
          command: |
            export WAVELENGTHS_VERSION=$(jq -r .version package.json | tr -d '"')
            helm repo update
            helm upgrade --install wavelengths beantown/wavelengths \
              --namespace prod \
              --set global.env=prod \
              --set image.tag=$WAVELENGTHS_VERSION \
              --debug

workflows:
  version: 2
  on_commit:
    jobs:
      - lint
      - build_and_publish:
          requires:
            - lint
      - deploy:
          requires:
            - build_and_publish
